export const WEEKLY = [
  { value: 'mondays', label: 'Mondays' },
  { value: 'tuesdays', label: 'Tuesdays' },
  { value: 'wednesdays', label: 'Wednesdays' },
  { value: 'thursdays', label: 'Thursdays' },
  { value: 'fridays', label: 'Fridays' },
  { value: 'saturdays', label: 'Saturdays' },
  { value: 'sundays', label: 'Sundays' }
]

export const MONTHLY = [
  { value: '1', label: '1st' },
  { value: '2', label: '2nd' },
  { value: '3', label: '3r' },
  { value: '4', label: '4t' },
  { value: '5', label: '5t' },
  { value: '6', label: '6t' },
  { value: '7', label: '7th' },
  { value: '8', label: '8th' },
  { value: '9', label: '9th' },
  { value: '10', label: '10th' },
  { value: '11', label: '11th' },
  { value: '12', label: '12th' },
  { value: '13', label: '13th' },
  { value: '14', label: '14th' },
  { value: '15', label: '15th' },
  { value: '16', label: '16th' },
  { value: '17', label: '17th' },
  { value: '18', label: '18th' },
  { value: '19', label: '19th' },
  { value: '20', label: '20th' },
  { value: '21', label: '21st' },
  { value: '22', label: '22nd' },
  { value: '23', label: '23rd' },
  { value: '24', label: '24th' },
  { value: '25', label: '25th' },
  { value: '26', label: '26th' },
  { value: '27', label: '27th' },
  { value: '28', label: '28th' },
  { value: '29', label: '29th' },
  { value: '30', label: '30th' },
  { value: '31', label: '31st' }
]

export const custom = [
  { value: '1', label: 'Every 1st' },
  { value: '2', label: 'Every 2nd' },
  { value: '3', label: 'Every 3rd' },
  { value: '4', label: 'Every 4th' },
  { value: '5', label: 'Every 5th' },
  { value: '6', label: 'Every 6th' },
  { value: '7', label: 'Every 7th' },
  { value: '8', label: 'Every 8th' },
  { value: '9', label: 'Every 9th' },
  { value: '10', label: 'Every 10th' },
  { value: '11', label: 'Every 11th' },
  { value: '12', label: 'Every 12th' },
  { value: '13', label: 'Every 13th' },
  { value: '14', label: 'Every 14th' },
  { value: '15', label: 'Every 15th' },
  { value: '16', label: 'Every 16th' },
  { value: '17', label: 'Every 17th' },
  { value: '18', label: 'Every 18th' },
  { value: '19', label: 'Every 19th' },
  { value: '20', label: 'Every 20th' },
  { value: '21', label: 'Every 21st' },
  { value: '22', label: 'Every 22nd' },
  { value: '23', label: 'Every 23rd' },
  { value: '24', label: 'Every 24th' },
  { value: '25', label: 'Every 25th' },
  { value: '26', label: 'Every 26th' },
  { value: '27', label: 'Every 27th' },
  { value: '28', label: 'Every 28th' },
  { value: '29', label: 'Every 29th' },
  { value: '30', label: 'Every 30th' },
  { value: '31', label: 'Every 31st' }
]
