export const TIMEZONES = [
  { value: 'UM12', label: '(UTC -12:00) Baker/Howland Island' },
  { value: 'UM11', label: '(UTC -11:00) Samoa Time Zone, Niue' },
  { value: 'UM10', label: '(UTC -10:00) Hawaii-Aleutian Standard Time, Cook Islands, Tahiti' },
  { value: 'UM95', label: '(UTC -9:30) Marquesas Islands' },
  { value: 'UM9', label: '(UTC -9:00) Alaska Standard Time, Gambier Islands' },
  { value: 'UM8', label: '(UTC -8:00) Pacific Standard Time, Clipperton Island' },
  { value: 'UM7', label: '(UTC -7:00) Mountain Standard Time' },
  { value: 'UM6', label: '(UTC -6:00) Central Standard Time' },
  { value: 'UM5', label: '(UTC -5:00) Eastern Standard Time, Western Caribbean Standard Time' },
  { value: 'UM45', label: '(UTC -4:30) Venezuelan Standard Time' },
  { value: 'UM4', label: '(UTC -4:00) Atlantic Standard Time, Eastern Caribbean Standard Time' },
  { value: 'UM35', label: '(UTC -3:30) Newfoundland Standard Time' },
  { value: 'UM3', label: '(UTC -3:00) Argentina, Brazil, French Guiana, Uruguay' },
  { value: 'UM2', label: '(UTC -2:00) South Georgia/South Sandwich Islands' },
  { value: 'UM1', label: '(UTC -1:00) Azores, Cape Verde Islands' },
  { value: 'UTC', label: '(UTC) Greenwich Mean Time, Western European Time' },
  { value: 'UP1', label: '(UTC +1:00) Central European Time, West Africa Time' },
  { value: 'UP2', label: '(UTC +2:00) Central Africa Time, Eastern European Time, Kaliningrad Time' },
  { value: 'UP3', label: '(UTC +3:00) Moscow Time, East Africa Time' },
  { value: 'UP35', label: '(UTC +3:30) Iran Standard Time' },
  { value: 'UP4', label: '(UTC +4:00) Azerbaijan Standard Time, Samara Time' },
  { value: 'UP45', label: '(UTC +4:30) Afghanistan' },
  { value: 'UP5', label: '(UTC +5:00) Pakistan Standard Time, Yekaterinburg Time' },
  { value: 'UP55', label: '(UTC +5:30) Indian Standard Time, Sri Lanka Time' },
  { value: 'UP575', label: '(UTC +5:45) Nepal Time' },
  { value: 'UP6', label: '(UTC +6:00) Bangladesh Standard Time, Bhutan Time, Omsk Time' },
  { value: 'UP65', label: '(UTC +6:30) Cocos Islands, Myanmar' },
  { value: 'UP7', label: '(UTC +7:00) Krasnoyarsk Time, Cambodia, Laos, Thailand, Vietnam' },
  { value: 'UP8', label: '(UTC +8:00) Australian Western Standard Time, Beijing Time, Irkutsk Time' },
  { value: 'UP875', label: '(UTC +8:45) Australian Central Western Standard Time' },
  { value: 'UP9', label: '(UTC +9:00) Japan Standard Time, Korea Standard Time, Yakutsk Time' },
  { value: 'UP95', label: '(UTC +9:30) Australian Central Standard Time' },
  { value: 'UP10', label: '(UTC +10:00) Australian Eastern Standard Time, Vladivostok Time' },
  { value: 'UP105', label: '(UTC +10:30) Lord Howe Island' },
  { value: 'UP11', label: '(UTC +11:00) Magadan Time, Solomon Islands, Vanuatu' },
  { value: 'UP115', label: '(UTC +11:30) Norfolk Island' },
  { value: 'UP12', label: '(UTC +12:00) Fiji, Gilbert Islands, Kamchatka Time, New Zealand Standard Time' },
  { value: 'UP1275', label: '(UTC +12:45) Chatham Islands Standard Time' },
  { value: 'UP13', label: '(UTC +13:00) Phoenix Islands Time, Tonga' },
  { value: 'UP14', label: '(UTC +14:00) Line Islands' }
]
