// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'INVOICES/'

/*
  Invoices
*/
export const FETCH_INVOICES_REJECTED = globalIdent + 'FETCH_INVOICES_REJECTED'
export const FETCH_INVOICES_REQUESTED = globalIdent + 'FETCH_INVOICES_REQUESTED'
export const FETCH_INVOICES_SUCCEDED = globalIdent + 'FETCH_INVOICES_SUCCEDED'

export const FETCH_INVOICE_DETAIL_REJECTED = globalIdent + 'FETCH_INVOICE_DETAIL_REJECTED'
export const FETCH_INVOICE_DETAIL_REQUESTED = globalIdent + 'FETCH_INVOICE_DETAIL_REQUESTED'
export const FETCH_INVOICE_DETAIL_SUCCEDED = globalIdent + 'FETCH_INVOICE_DETAIL_SUCCEDED'

export const UPDATE_INVOICE_REJECTED = globalIdent + 'UPDATE_INVOICE_REJECTED'
export const UPDATE_INVOICE_REQUESTED = globalIdent + 'UPDATE_INVOICE_REQUESTED'
export const UPDATE_INVOICE_SUCCEDED = globalIdent + 'UPDATE_INVOICE_SUCCEDED'

export const EMAIL_SELECTED_INVOICES_REJECTED = globalIdent + 'EMAIL_SELECTED_INVOICES_REJECTED'
export const EMAIL_SELECTED_INVOICES_REQUESTED = globalIdent + 'EMAIL_SELECTED_INVOICES_REQUESTED'
export const EMAIL_SELECTED_INVOICES_SUCCEDED = globalIdent + 'EMAIL_SELECTED_INVOICES_SUCCEDED'

export const DELETE_INVOICES_REJECTED = globalIdent + 'DELETE_INVOICES_REJECTED'
export const DELETE_INVOICES_REQUESTED = globalIdent + 'DELETE_INVOICES_REQUESTED'
export const DELETE_INVOICES_SUCCEDED = globalIdent + 'DELETE_INVOICES_SUCCEDED'
export const DELETE_INVOICES_OF_CUSTOMER_SUCCEDED = globalIdent + 'DELETE_INVOICES_OF_CUSTOMER_SUCCEDED'

export const CREATE_INVOICES_REQUESTED = globalIdent + 'CREATE_INVOICES_REQUESTED'
export const CREATE_INVOICES_SUCCEDED = globalIdent + 'CREATE_INVOICES_SUCCEDED'
export const CREATE_INVOICES_REJECTED = globalIdent + 'CREATE_INVOICES_REJECTED'
