// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'SERVICES/'

export const CREATE_SERVICE_REQUESTED = globalIdent + 'CREATE_SERVICE_REQUESTED'
export const CREATE_SERVICE_SUCCEDED = globalIdent + 'CREATE_SERVICE_SUCCEDED'
export const CREATE_SERVICE_REJECTED = globalIdent + 'CREATE_SERVICE_REJECTED'

export const FETCH_SERVICE_REJECTED = globalIdent + 'FETCH_SERVICE_REJECTED'
export const FETCH_SERVICE_REQUESTED = globalIdent + 'FETCH_SERVICE_REQUESTED'
export const FETCH_SERVICE_SUCCEDED = globalIdent + 'FETCH_SERVICE_SUCCEDED'

export const FETCH_SERVICES_REJECTED = globalIdent + 'FETCH_SERVICES_REJECTED'
export const FETCH_SERVICES_REQUESTED = globalIdent + 'FETCH_SERVICES_REQUESTED'
export const FETCH_SERVICES_SUCCEDED = globalIdent + 'FETCH_SERVICES_SUCCEDED'

export const FETCH_FULL_SERVICES_REJECTED = globalIdent + 'FETCH_FULL_SERVICES_REJECTED'
export const FETCH_FULL_SERVICES_REQUESTED = globalIdent + 'FETCH_FULL_SERVICES_REQUESTED'
export const FETCH_FULL_SERVICES_SUCCEDED = globalIdent + 'FETCH_FULL_SERVICES_SUCCEDED'

export const PUSH_NEW_SERVICE_LOCALLY = globalIdent + 'PUSH_NEW_SERVICE_LOCALLY'
export const REMOVE_NEW_LOCAL_SERVICES = globalIdent + 'REMOVE_NEW_LOCAL_SERVICES'

export const UPDATE_SERVICE_REJECTED = globalIdent + 'UPDATE_SERVICE_REJECTED'
export const UPDATE_SERVICE_REQUESTED = globalIdent + 'UPDATE_SERVICE_REQUESTED'
export const UPDATE_SERVICE_SUCCEDED = globalIdent + 'UPDATE_SERVICE_SUCCEDED'

export const SET_SERVICE_EDITMODE_LOCALLY = globalIdent + 'SET_SERVICE_EDITMODE_LOCALLY'
export const SORT_SERVICE_LOCALLY = globalIdent + 'SORT_SERVICE_LOCALLY'

export const ARCHIVE_SERVICE_SUCCEDED = globalIdent + 'ARCHIVE_SERVICE_SUCCEDED'

export const REMOVE_UPDATED_SERVICE = globalIdent + 'REMOVE_UPDATED_SERVICE'
