// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'WALKERS/'

export const FETCH_WALKERS_REJECTED = globalIdent + 'FETCH_WALKERS_REJECTED'
export const FETCH_WALKERS_REQUESTED = globalIdent + 'FETCH_WALKERS_REQUESTED'
export const FETCH_WALKERS_SUCCEDED = globalIdent + 'FETCH_WALKERS_SUCCEDED'

export const FETCH_WALKER_PROFILE_REJECTED = globalIdent + 'FETCH_WALKERS_REJECTED'
export const FETCH_WALKER_PROFILE_REQUESTED = globalIdent + 'FETCH_WALKERS_REQUESTED'
export const FETCH_WALKER_PROFILE_SUCCEDED = globalIdent + 'FETCH_WALKERS_SUCCEDED'

export const EDIT_WALKER_PROFILE_REJECTED = globalIdent + 'EDIT_WALKER_PROFILE_REJECTED'
export const EDIT_WALKER_PROFILE_REQUESTED = globalIdent + 'EDIT_WALKER_PROFILE_REQUESTED'
export const EDIT_WALKER_PROFILE_SUCCEDED = globalIdent + 'EDIT_WALKER_PROFILE_SUCCEDED'

export const ADD_WALKER_REJECTED = globalIdent + 'ADD_WALKER_REJECTED'
export const ADD_WALKER_REQUESTED = globalIdent + 'ADD_WALKER_REQUESTED'
export const ADD_WALKER_SUCCEDED = globalIdent + 'ADD_WALKER_SUCCEDED'

export const TOGGLE_WALKER_PROFILE_STATUS_REJECTED = globalIdent + 'TOGGLE_WALKER_PROFILE_STATUS_REJECTED'
export const TOGGLE_WALKER_PROFILE_STATUS_REQUESTED = globalIdent + 'TOGGLE_WALKER_PROFILE_STATUS_REQUESTED'
export const TOGGLE_WALKER_PROFILE_STATUS_SUCCEDED = globalIdent + 'TOGGLE_WALKER_PROFILE_STATUS_SUCCEDED'

/*
  Walkers payroll
*/
export const FETCH_WALKER_PAYROLL_REJECTED = globalIdent + 'FETCH_WALKER_PAYROLL_REJECTED'
export const FETCH_WALKER_PAYROLL_REQUESTED = globalIdent + 'FETCH_WALKER_PAYROLL_REQUESTED'
export const FETCH_WALKER_PAYROLL_SUCCEDED = globalIdent + 'FETCH_WALKER_PAYROLL_SUCCEDED'

/*
  Walkers payrate
*/
export const FETCH_WALKER_PAYRATE_REJECTED = globalIdent + 'FETCH_WALKER_PAYRATE_REJECTED'
export const FETCH_WALKER_PAYRATE_REQUESTED = globalIdent + 'FETCH_WALKER_PAYRATE_REQUESTED'
export const FETCH_WALKER_PAYRATE_SUCCEDED = globalIdent + 'FETCH_WALKER_PAYRATE_SUCCEDED'

export const EDIT_WALKER_PAYRATE_REJECTED = globalIdent + 'EDIT_WALKER_PAYRATE_REJECTED'
export const EDIT_WALKER_PAYRATE_REQUESTED = globalIdent + 'EDIT_WALKER_PAYRATE_REQUESTED'
export const EDIT_WALKER_PAYRATE_SUCCEDED = globalIdent + 'EDIT_WALKER_PAYRATE_SUCCEDED'

/*
  Walkers addons
*/
export const ADD_WALKER_ADDON_REJECTED = globalIdent + 'FETCH_WALKER_ADDON_REJECTED'
export const ADD_WALKER_ADDON_REQUESTED = globalIdent + 'FETCH_WALKER_ADDON_REQUESTED'
export const ADD_WALKER_ADDON_SUCCEDED = globalIdent + 'FETCH_WALKER_ADDON_SUCCEDED'
/*
  Walkers services
*/
export const ADD_WALKER_SERVICE_REJECTED = globalIdent + 'FETCH_WALKER_SERVICE_REJECTED'
export const ADD_WALKER_SERVICE_REQUESTED = globalIdent + 'FETCH_WALKER_SERVICE_REQUESTED'
export const ADD_WALKER_SERVICE_SUCCEDED = globalIdent + 'FETCH_WALKER_SERVICE_SUCCEDED'

export const UPDATE_PROFILE_EDIT_MODE = globalIdent + 'UPDATE_PROFILE_EDIT_MODE'
export const UPDATE_SECURITY_EDIT_MODE = globalIdent + 'UPDATE_SECURITY_EDIT_MODE'
