// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'ADDONS/'

export const ARCHIVE_ADDON_REQUESTED = globalIdent + 'ARCHIVE_ADDON_REQUESTED'
export const ARCHIVE_ADDON_SUCCEDED = globalIdent + 'ARCHIVE_ADDON_SUCCEDED'
export const ARCHIVE_ADDON_REJECTED = globalIdent + 'ARCHIVE_ADDON_REJECTED'

export const CREATE_ADDON_REQUESTED = globalIdent + 'CREATE_ADDON_REQUESTED'
export const CREATE_ADDON_SUCCEDED = globalIdent + 'CREATE_ADDON_SUCCEDED'
export const CREATE_ADDON_REJECTED = globalIdent + 'CREATE_ADDON_REJECTED'

export const FETCH_ADDONS_REJECTED = globalIdent + 'FETCH_ADDONS_REJECTED'
export const FETCH_ADDONS_REQUESTED = globalIdent + 'FETCH_ADDONS_REQUESTED'
export const FETCH_ADDONS_SUCCEDED = globalIdent + 'FETCH_ADDONS_SUCCEDED'

export const FETCH_ADDON_REJECTED = globalIdent + 'FETCH_ADDON_REJECTED'
export const FETCH_ADDON_REQUESTED = globalIdent + 'FETCH_ADDON_REQUESTED'
export const FETCH_ADDON_SUCCEDED = globalIdent + 'FETCH_ADDON_SUCCEDED'

export const FETCH_FULL_ADDONS_REJECTED = globalIdent + 'FETCH_FULL_ADDONS_REJECTED'
export const FETCH_FULL_ADDONS_REQUESTED = globalIdent + 'FETCH_FULL_ADDONS_REQUESTED'
export const FETCH_FULL_ADDONS_SUCCEDED = globalIdent + 'FETCH_FULL_ADDONS_SUCCEDED'

export const PUSH_NEW_ADDON_LOCALLY = globalIdent + 'PUSH_NEW_ADDON_LOCALLY'
export const REMOVE_NEW_LOCAL_ADDONS = globalIdent + 'REMOVE_NEW_LOCAL_ADDONS'
export const REMOVE_UPDATED_ADDON = globalIdent + 'REMOVE_UPDATED_ADDON'

export const UPDATE_ADDON_REQUESTED = globalIdent + 'UPDATE_ADDON_REQUESTED'
export const UPDATE_ADDON_SUCCEDED = globalIdent + 'UPDATE_ADDON_SUCCEDED'
export const UPDATE_ADDON_REJECTED = globalIdent + 'UPDATE_ADDON_REJECTED'

export const SET_ADDON_EDITMODE_LOCALLY = globalIdent + 'SET_ADDON_EDITMODE_LOCALLY'
