// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'PAYMENTS/'

/*
  Payments
*/
export const FETCH_PAYMENTS_REJECTED = globalIdent + 'FETCH_PAYMENTS_REJECTED'
export const FETCH_PAYMENTS_REQUESTED = globalIdent + 'FETCH_PAYMENTS_REQUESTED'
export const FETCH_PAYMENTS_SUCCEDED = globalIdent + 'FETCH_PAYMENTS_SUCCEDED'

export const UPDATE_PAYMENTS_REJECTED = globalIdent + 'UPDATE_PAYMENTS_REJECTED'
export const UPDATE_PAYMENTS_REQUESTED = globalIdent + 'UPDATE_PAYMENTS_REQUESTED'
export const UPDATE_PAYMENTS_SUCCEDED = globalIdent + 'UPDATE_PAYMENTS_SUCCEDED'

export const CREDITS_ERROR = 'Error::UPDATE_PAYMENTS_REJECTED'

export const FETCH_BILLING_REJECTED = globalIdent + 'FETCH_BILLING_REJECTED'
export const FETCH_BILLING_REQUESTED = globalIdent + 'FETCH_BILLING_REQUESTED'
export const FETCH_BILLING_SUCCEDED = globalIdent + 'FETCH_BILLING_SUCCEDED'

export const UPDATE_BILLING_PAYMENTS_REJECTED = globalIdent + 'UPDATE_BILLING_PAYMENTS_REJECTED'
export const UPDATE_BILLING_PAYMENTS_REQUESTED = globalIdent + 'UPDATE_BILLING_PAYMENTS_REQUESTED'
export const UPDATE_BILLING_PAYMENTS_SUCCEDED = globalIdent + 'UPDATE_BILLING_PAYMENTS_SUCCEDED'

export const RECEIVE_PAYMENTS_REJECTED = globalIdent + 'RECEIVE_PAYMENTS_REJECTED'
export const RECEIVE_PAYMENTS_REQUESTED = globalIdent + 'RECEIVE_PAYMENTS_REQUESTED'
export const RECEIVE_PAYMENTS_SUCCEDED = globalIdent + 'RECEIVE_PAYMENTS_SUCCEDED'
