// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'REPORTS/'
/*
  Reports
*/
export const FETCH_ACTIVITY_REPORT_REJECTED = globalIdent + 'FETCH_ACTIVITY_REPORT_REJECTED'
export const FETCH_ACTIVITY_REPORT_REQUESTED = globalIdent + 'FETCH_ACTIVITY_REPORT_REQUESTED'
export const FETCH_ACTIVITY_REPORT_SUCCEDED = globalIdent + 'FETCH_ACTIVITY_REPORT_SUCCEDED'

export const FETCH_CUSTOMERMAIL_REPORT_REJECTED = globalIdent + 'FETCH_CUSTOMERMAIL_REPORT_REJECTED'
export const FETCH_CUSTOMERMAIL_REPORT_REQUESTED = globalIdent + 'FETCH_CUSTOMERMAIL_REPORT_REQUESTED'
export const FETCH_CUSTOMERMAIL_REPORT_SUCCEDED = globalIdent + 'FETCH_CUSTOMERMAIL_REPORT_SUCCEDED'

export const FETCH_DISBURSEMENT_REPORT_REJECTED = globalIdent + 'FETCH_DISBURSEMENT_REPORT_REJECTED'
export const FETCH_DISBURSEMENT_REPORT_REQUESTED = globalIdent + 'FETCH_DISBURSEMENT_REPORT_REQUESTED'
export const FETCH_DISBURSEMENT_REPORT_SUCCEDED = globalIdent + 'FETCH_DISBURSEMENT_REPORT_SUCCEDED'

export const FETCH_DISBURSEMENT_DETAIL_SUCCEDED = globalIdent + 'FETCH_DISBURSEMENT_DETAIL_SUCCEDED'
export const FETCH_DISBURSEMENT_DETAIL_REJECTED = globalIdent + 'FETCH_DISBURSEMENT_DETAIL_REJECTED'
export const CLEAR_DISBURSEMENT_DETAIL = globalIdent + 'CLEAR_DISBURSEMENT_DETAIL'

export const FETCH_QRCODES_REPORT_REJECTED = globalIdent + 'FETCH_QRCODES_REPORT_REJECTED'
export const FETCH_QRCODES_REPORT_REQUESTED = globalIdent + 'FETCH_QRCODES_REPORT_REQUESTED'
export const FETCH_QRCODES_REPORT_SUCCEDED = globalIdent + 'FETCH_QRCODES_REPORT_SUCCEDED'

export const FETCH_RECEIVABLES_REPORT_REJECTED = globalIdent + 'FETCH_RECEIVABLES_REPORT_REJECTED'
export const FETCH_RECEIVABLES_REPORT_REQUESTED = globalIdent + 'FETCH_RECEIVABLES_REPORT_REQUESTED'
export const FETCH_RECEIVABLES_REPORT_SUCCEDED = globalIdent + 'FETCH_RECEIVABLES_REPORT_SUCCEDED'

export const FETCH_WALKAUDIT_REPORT_REJECTED = globalIdent + 'FETCH_WALKAUDIT_REPORT_REJECTED'
export const FETCH_WALKAUDIT_REPORT_REQUESTED = globalIdent + 'FETCH_WALKAUDIT_REPORT_REQUESTED'
export const FETCH_WALKAUDIT_REPORT_SUCCEDED = globalIdent + 'FETCH_WALKAUDIT_REPORT_SUCCEDED'

export const FETCH_TRANSACTION_REPORT_REJECTED = globalIdent + 'FETCH_TRANSACTION_REPORT_REJECTED'
export const FETCH_TRANSACTION_REPORT_REQUESTED = globalIdent + 'FETCH_TRANSACTION_REPORT_REQUESTED'
export const FETCH_TRANSACTION_REPORT_SUCCEDED = globalIdent + 'FETCH_TRANSACTION_REPORT_SUCCEDED'

export const FETCH_SALES_REPORT_REJECTED = globalIdent + 'FETCH_SALES_REPORT_REJECTED'
export const FETCH_SALES_REPORT_REQUESTED = globalIdent + 'FETCH_SALES_REPORT_REQUESTED'
export const FETCH_SALES_REPORT_SUCCEDED = globalIdent + 'FETCH_SALES_REPORT_SUCCEDED'

export const FETCH_STAFFPAYROLL_REPORT_REJECTED = globalIdent + 'FETCH_STAFFPAYROLL_REPORT_REJECTED'
export const FETCH_STAFFPAYROLL_REPORT_REQUESTED = globalIdent + 'FETCH_STAFFPAYROLL_REPORT_REQUESTED'
export const FETCH_STAFFPAYROLL_REPORT_SUCCEDED = globalIdent + 'FETCH_STAFFPAYROLL_REPORT_SUCCEDED'

export const FETCH_CUSTOMER_INFO_REJECTED = globalIdent + 'FETCH_CUSTOMER_INFO_REJECTED'
export const FETCH_CUSTOMER_INFO_REQUESTED = globalIdent + 'FETCH_CUSTOMER_INFO_REQUESTED'
export const FETCH_CUSTOMER_INFO_SUCCEDED = globalIdent + 'FETCH_CUSTOMER_INFO_SUCCEDED'

export const DOWNLOAD_REPORT_REJECTED = globalIdent + 'DOWNLOAD_REPORT_REJECTED'
export const DOWNLOAD_REPORT_REQUESTED = globalIdent + 'DOWNLOAD_REPORT_REQUESTED'
export const DOWNLOAD_REPORT_SUCCEDED = globalIdent + 'DOWNLOAD_REPORT_SUCCEDED'

export const FETCH_PAYROLL_REPORT_REJECTED = globalIdent + 'FETCH_PAYROLL_REPORT_REJECTED'
export const FETCH_PAYROLL_REPORT_REQUESTED = globalIdent + 'FETCH_PAYROLL_REPORT_REQUESTED'
export const FETCH_PAYROLL_REPORT_SUCCEDED = globalIdent + 'FETCH_PAYROLL_REPORT_SUCCEDED'
