// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'SETTINGS/'

// Settings Addons
export const FETCH_SETTINGS_ADDONS_REJECTED = globalIdent + 'FETCH_SETTINGS_ADDONS_REJECTED'
export const FETCH_SETTINGS_ADDONS_REQUESTED = globalIdent + 'FETCH_SETTINGS_ADDONS_REQUESTED'
export const FETCH_SETTINGS_ADDONS_SUCCEDED = globalIdent + 'FETCH_SETTINGS_ADDONS_SUCCEDED'

// Settings Customer Billing
export const POST_CUSTOMER_BILLING_REJECTED = globalIdent + 'POST_CUSTOMER_BILLING_REJECTED'
export const POST_CUSTOMER_BILLING_REQUESTED = globalIdent + 'POST_CUSTOMER_BILLING_REQUESTED'
export const POST_CUSTOMER_BILLING_SUCCEDED = globalIdent + 'POST_CUSTOMER_BILLING_SUCCEDED'

// Settings Profile
export const FETCH_SETTINGS_PROFILE_REJECTED = globalIdent + 'FETCH_SETTINGS_PROFILE_REJECTED'
export const FETCH_SETTINGS_PROFILE_REQUESTED = globalIdent + 'FETCH_SETTINGS_PROFILE_REQUESTED'
export const FETCH_SETTINGS_PROFILE_SUCCEDED = globalIdent + 'FETCH_SETTINGS_PROFILE_SUCCEDED'

// Settings Services
export const PUSH_NEW_SERVICE_LOCALLY = globalIdent + 'PUSH_NEW_SERVICE_LOCALLY'
export const FETCH_SETTINGS_SERVICES_REJECTED = globalIdent + 'FETCH_SETTINGS_SERVICES_REJECTED'
export const FETCH_SETTINGS_SERVICES_REQUESTED = globalIdent + 'FETCH_SETTINGS_SERVICES_REQUESTED'
export const FETCH_SETTINGS_SERVICES_SUCCEDED = globalIdent + 'FETCH_SETTINGS_SERVICES_SUCCEDED'

// Settings Scheduler
export const FETCH_SETTINGS_SCHEDULER_REJECTED = globalIdent + 'FETCH_SETTINGS_SCHEDULER_REJECTED'
export const FETCH_SETTINGS_SCHEDULER_REQUESTED = globalIdent + 'FETCH_SETTINGS_SCHEDULER_REQUESTED'
export const FETCH_SETTINGS_SCHEDULER_SUCCEDED = globalIdent + 'FETCH_SETTINGS_SCHEDULER_SUCCEDED'
