// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'PROFILE/'

/*
Bank Information
 */
export const FETCH_PROFILE_BANK_INFORMATION_REJECTED = globalIdent + 'FETCH_PROFILE_BANK_INFORMATION_REJECTED'
export const FETCH_PROFILE_BANK_INFORMATION_REQUESTED = globalIdent + 'FETCH_PROFILE_BANK_INFORMATION_REQUESTED'
export const FETCH_PROFILE_BANK_INFORMATION_SUCCEDED = globalIdent + 'FETCH_PROFILE_BANK_INFORMATION_SUCCEDED'

export const UPDATE_PROFILE_BANK_INFORMATION_REJECTED = globalIdent + 'UPDATE_PROFILE_BANK_INFORMATION_REJECTED'
export const UPDATE_PROFILE_BANK_INFORMATION_REQUESTED = globalIdent + 'UPDATE_PROFILE_BANK_INFORMATION_REQUESTED'
export const UPDATE_PROFILE_BANK_INFORMATION_SUCCEDED = globalIdent + 'UPDATE_PROFILE_BANK_INFORMATION_SUCCEDED'

/*
Basic profile
 */
export const FETCH_PROFILE_BASIC_PROFILE_REJECTED = globalIdent + 'FETCH_PROFILE_BASIC_PROFILE_REJECTED'
export const FETCH_PROFILE_BASIC_PROFILE_REQUESTED = globalIdent + 'FETCH_PROFILE_BASIC_PROFILE_REQUESTED'
export const FETCH_PROFILE_BASIC_PROFILE_SUCCEDED = globalIdent + 'FETCH_PROFILE_BASIC_PROFILE_SUCCEDED'

export const UPDATE_PROFILE_BASIC_PROFILE_REJECTED = globalIdent + 'UPDATE_PROFILE_BASIC_PROFILE_REJECTED'
export const UPDATE_PROFILE_BASIC_PROFILE_REQUESTED = globalIdent + 'UPDATE_PROFILE_BASIC_PROFILE_REQUESTED'
export const UPDATE_PROFILE_BASIC_PROFILE_SUCCEDED = globalIdent + 'UPDATE_PROFILE_BASIC_PROFILE_SUCCEDED'

/*
Billing information
 */
export const FETCH_PROFILE_BILLING_INFORMATION_REJECTED = globalIdent + 'FETCH_PROFILE_BILLING_INFORMATION_REJECTED'
export const FETCH_PROFILE_BILLING_INFORMATION_REQUESTED = globalIdent + 'FETCH_PROFILE_BILLING_INFORMATION_REQUESTED'
export const FETCH_PROFILE_BILLING_INFORMATION_SUCCEDED = globalIdent + 'FETCH_PROFILE_BILLING_INFORMATION_SUCCEDED'

export const UPDATE_PROFILE_BILLING_INFORMATION_REJECTED = globalIdent + 'UPDATE_PROFILE_BILLING_INFORMATION_REJECTED'
export const UPDATE_PROFILE_BILLING_INFORMATION_REQUESTED = globalIdent + 'UPDATE_PROFILE_BILLING_INFORMATION_REQUESTED'
export const UPDATE_PROFILE_BILLING_INFORMATION_SUCCEDED = globalIdent + 'UPDATE_PROFILE_BILLING_INFORMATION_SUCCEDED'

/*
Feedback
 */
export const SEND_FEEDBACK_REJECTED = globalIdent + 'SEND_FEEDBACK_REJECTED'
export const SEND_FEEDBACK_REQUESTED = globalIdent + 'SEND_FEEDBACK_REQUESTED'
export const SEND_FEEDBACK_SUCCEDED = globalIdent + 'SEND_FEEDBACK_SUCCEDED'

/*
Passwords
 */
export const UPDATE_PROFILE_PASSWORD_REJECTED = globalIdent + 'UPDATE_PROFILE_PASSWORD_REJECTED'
export const UPDATE_PROFILE_PASSWORD_REQUESTED = globalIdent + 'UPDATE_PROFILE_PASSWORD_REQUESTED'
export const UPDATE_PROFILE_PASSWORD_SUCCEDED = globalIdent + 'UPDATE_PROFILE_PASSWORD_SUCCEDED'

/*
Payment Information
 */
export const FETCH_PROFILE_PAYMENT_INFORMATION_REJECTED = globalIdent + 'FETCH_PROFILE_PAYMENT_INFORMATION_REJECTED'
export const FETCH_PROFILE_PAYMENT_INFORMATION_REQUESTED = globalIdent + 'FETCH_PROFILE_PAYMENT_INFORMATION_REQUESTED'
export const FETCH_PROFILE_PAYMENT_INFORMATION_SUCCEDED = globalIdent + 'FETCH_PROFILE_PAYMENT_INFORMATION_SUCCEDED'

export const UPDATE_PROFILE_PAYMENT_INFORMATION_REJECTED = globalIdent + 'UPDATE_PROFILE_PAYMENT_INFORMATION_REJECTED'
export const UPDATE_PROFILE_PAYMENT_INFORMATION_REQUESTED = globalIdent + 'UPDATE_PROFILE_PAYMENT_INFORMATION_REQUESTED'
export const UPDATE_PROFILE_PAYMENT_INFORMATION_SUCCEDED = globalIdent + 'UPDATE_PROFILE_PAYMENT_INFORMATION_SUCCEDED'

/*
Profile Picture
 */
export const FETCH_PROFILE_PROFILE_PICTURE_REJECTED = globalIdent + 'FETCH_PROFILE_PROFILE_PICTURE_REJECTED'
export const FETCH_PROFILE_PROFILE_PICTURE_REQUESTED = globalIdent + 'FETCH_PROFILE_PROFILE_PICTURE_REQUESTED'
export const FETCH_PROFILE_PROFILE_PICTURE_SUCCEDED = globalIdent + 'FETCH_PROFILE_PROFILE_PICTURE_SUCCEDED'

export const UPDATE_PROFILE_PROFILE_PICTURE_REJECTED = globalIdent + 'UPDATE_PROFILE_PROFILE_PICTURE_REJECTED'
export const UPDATE_PROFILE_PROFILE_PICTURE_REQUESTED = globalIdent + 'UPDATE_PROFILE_PROFILE_PICTURE_REQUESTED'
export const UPDATE_PROFILE_PROFILE_PICTURE_SUCCEDED = globalIdent + 'UPDATE_PROFILE_PROFILE_PICTURE_SUCCEDED'

/*
Qr Codes
 */
export const FETCH_PROFILE_QR_CODES_REJECTED = globalIdent + 'FETCH_PROFILE_QR_CODES_REJECTED'
export const FETCH_PROFILE_QR_CODES_REQUESTED = globalIdent + 'FETCH_PROFILE_QR_CODES_REQUESTED'
export const FETCH_PROFILE_QR_CODES_SUCCEDED = globalIdent + 'FETCH_PROFILE_QR_CODES_SUCCEDED'

export const UPDATE_PROFILE_QR_CODES_REJECTED = globalIdent + 'UPDATE_PROFILE_QR_CODES_REJECTED'
export const UPDATE_PROFILE_QR_CODES_REQUESTED = globalIdent + 'UPDATE_PROFILE_QR_CODES_REQUESTED'
export const UPDATE_PROFILE_QR_CODES_SUCCEDED = globalIdent + 'UPDATE_PROFILE_QR_CODES_SUCCEDED'

/*
Scheduler settings
 */
export const FETCH_PROFILE_SCHEDULER_SETTINGS_REJECTED = globalIdent + 'FETCH_PROFILE_SCHEDULER_SETTINGS_REJECTED'
export const FETCH_PROFILE_SCHEDULER_SETTINGS_REQUESTED = globalIdent + 'FETCH_PROFILE_SCHEDULER_SETTINGS_REQUESTED'
export const FETCH_PROFILE_SCHEDULER_SETTINGS_SUCCEDED = globalIdent + 'FETCH_PROFILE_SCHEDULER_SETTINGS_SUCCEDED'

export const UPDATE_PROFILE_SCHEDULER_SETTINGS_REJECTED = globalIdent + 'UPDATE_PROFILE_SCHEDULER_SETTINGS_REJECTED'
export const UPDATE_PROFILE_SCHEDULER_SETTINGS_REQUESTED = globalIdent + 'UPDATE_PROFILE_SCHEDULER_SETTINGS_REQUESTED'
export const UPDATE_PROFILE_SCHEDULER_SETTINGS_SUCCEDED = globalIdent + 'UPDATE_PROFILE_SCHEDULER_SETTINGS_SUCCEDED'

/*
Staff payroll
 */
export const FETCH_PROFILE_STAFF_PAYROLL_REJECTED = globalIdent + 'FETCH_PROFILE_STAFF_PAYROLL_REJECTED'
export const FETCH_PROFILE_STAFF_PAYROLL_REQUESTED = globalIdent + 'FETCH_PROFILE_STAFF_PAYROLL_REQUESTED'
export const FETCH_PROFILE_STAFF_PAYROLL_SUCCEDED = globalIdent + 'FETCH_PROFILE_STAFF_PAYROLL_SUCCEDED'

export const UPDATE_PROFILE_STAFF_PAYROLL_REJECTED = globalIdent + 'UPDATE_PROFILE_STAFF_PAYROLL_REJECTED'
export const UPDATE_PROFILE_STAFF_PAYROLL_REQUESTED = globalIdent + 'UPDATE_PROFILE_STAFF_PAYROLL_REQUESTED'
export const UPDATE_PROFILE_STAFF_PAYROLL_SUCCEDED = globalIdent + 'UPDATE_PROFILE_STAFF_PAYROLL_SUCCEDED'

export const UPDATE_LOGO_REQUESTED = globalIdent + 'UPDATE_LOGO_REQUESTED'
export const UPDATE_LOGO_SUCCEDED = globalIdent + 'UPDATE_LOGO_SUCCEDED'
export const UPDATE_LOGO_REJECTED = globalIdent + 'UPDATE_LOGO_REJECTED'

export const FETCH_LOGO_REQUESTED = globalIdent + 'FETCH_LOGO_REQUESTED'
export const FETCH_LOGO_SUCCEDED = globalIdent + 'FETCH_LOGO_SUCCEDED'
export const FETCH_LOGO_REJECTED = globalIdent + 'FETCH_LOGO_REJECTED'

export const FETCH_CUSTOMER_QRCODES_REQUESTED = globalIdent + 'FETCH_CUSTOMER_QRCODES_REQUESTED'
export const FETCH_CUSTOMER_QRCODES_SUCCEDED = globalIdent + 'FETCH_CUSTOMER_QRCODES_SUCCEDED'
export const FETCH_CUSTOMER_QRCODES_REJECTED = globalIdent + 'FETCH_CUSTOMER_QRCODES_REJECTED'
