// Constants
import { ACTIONS_BASE } from '../globals'

const globalIdent = ACTIONS_BASE + 'DASHBOARD/'

/*
  DailySnapshot
*/
export const FETCH_DAILY_SNAPSHOT_REJECTED = globalIdent + 'FETCH_DAILY_SNAPSHOT_REJECTED'
export const FETCH_DAILY_SNAPSHOT_REQUESTED = globalIdent + 'FETCH_DAILY_SNAPSHOT_REQUESTED'
export const FETCH_DAILY_SNAPSHOT_SUCCEDED = globalIdent + 'FETCH_DAILY_SNAPSHOT_SUCCEDED'

/*
  BusyHours
*/
export const FETCH_BUSY_HOURS_REJECTED = globalIdent + 'FETCH_BUSY_HOURS_REJECTED'
export const FETCH_BUSY_HOURS_REQUESTED = globalIdent + 'FETCH_BUSY_HOURS_REQUESTED'
export const FETCH_BUSY_HOURS_SUCCEDED = globalIdent + 'FETCH_BUSY_HOURS_SUCCEDED'

/*
  Revenue
*/
export const FETCH_REVENUE_REJECTED = globalIdent + 'FETCH_REVENUE_REJECTED'
export const FETCH_REVENUE_REQUESTED = globalIdent + 'FETCH_REVENUE_REQUESTED'
export const FETCH_REVENUE_SUCCEDED = globalIdent + 'FETCH_REVENUE_SUCCEDED'

/*
  CustomerBase
*/
export const FETCH_CUSTOMER_BASE_REJECTED = globalIdent + 'FETCH_CUSTOMER_BASE_REJECTED'
export const FETCH_CUSTOMER_BASE_REQUESTED = globalIdent + 'FETCH_CUSTOMER_BASE_REQUESTED'
export const FETCH_CUSTOMER_BASE_SUCCEDED = globalIdent + 'FETCH_CUSTOMER_BASE_SUCCEDED'

/*
  BusinessSnapshot
*/
export const FETCH_BUSINESS_SNAPSHOT_REJECTED = globalIdent + 'FETCH_BUSINESS_SNAPSHOT_REJECTED'
export const FETCH_BUSINESS_SNAPSHOT_REQUESTED = globalIdent + 'FETCH_BUSINESS_SNAPSHOT_REQUESTED'
export const FETCH_BUSINESS_SNAPSHOT_SUCCEDED = globalIdent + 'FETCH_BUSINESS_SNAPSHOT_SUCCEDED'

/*
  TopZips
*/
export const FETCH_TOP_ZIPS_REJECTED = globalIdent + 'FETCH_TOP_ZIPS_REJECTED'
export const FETCH_TOP_ZIPS_REQUESTED = globalIdent + 'FETCH_TOP_ZIPS_REQUESTED'
export const FETCH_TOP_ZIPS_SUCCEDED = globalIdent + 'FETCH_TOP_ZIPS_SUCCEDED'

/*
  ZipCodes
*/
export const FETCH_ZIP_CODES_REJECTED = globalIdent + 'FETCH_ZIP_CODES_REJECTED'
export const FETCH_ZIP_CODES_REQUESTED = globalIdent + 'FETCH_ZIP_CODES_REQUESTED'
export const FETCH_ZIP_CODES_SUCCEDED = globalIdent + 'FETCH_ZIP_CODES_SUCCEDED'
